### ISSUE TITLE
Implement additional zod methods

### ISSUE THREAD

**Issue by gordongest** [sam-goodwin/zod-class#13]
Similar to the earlier issue to implement `extend` in the `zod-class` interface, the TS interpreter does not currently expect class instances to have methods such as `omit`, `pick`, `partial`, or `passthrough`. These methods would be useful for cases such as building `MongoDB` documents for insertion where the `_id` field is required but does not exist until the document has been returned by the cluster, where that field is assigned by the engine.

**Comment by sam-goodwin** [comment]
Do you mean something like this?

```ts
class Foo extends Z.class({ 
  foo: z.string(),
  bar: z.string()
}) {}

class Bar extends Foo.pick("foo") {}
```

Should you be able to pick and extend at the same time or should you be expected to chain them?

```ts
// inline
class Bar extends Foo.pick("foo", {
  bar: z.number()
}) {}

// with chaining
class Bar extends Foo.pick("foo").extend({
  bar: z.number()
}) {}
```

When it comes to chaining, I would worry about building up large prototype chains (class hierarchies). They aren't "free" computationally.

Does this look like the right DX for `.passthrough`?
```ts
class Foo extends Z.class({
  foo: z.string()
}).passthrough() {}
```

**Comment by sam-goodwin** [comment]
> These methods would be useful for cases such as building MongoDB documents for insertion where the _id field is required but does not exist until the document has been returned by the cluster, where that field is assigned by the engine

Can you share an example of what you'd like to do? I'm very interested in understanding how it would help with Mongo

**Comment by sam-goodwin** [comment]
Looks like we're drawing from this list of object-specific helpers: https://github.com/colinhacks/zod#objects

**Comment by gordongest** [comment]
Not necessarily in the scope of defining a class, more along the lines of creating an instance. 

Something along the lines of:
```
class Foo extends Z.class({
  _id: z.instanceof(ObjectId),
  bar: z.number(),
  baz: z.string()
}) {};

const omitBaz = Foo.omit({ _id: true }).parse({
  bar: 42,
  baz: 'baz',
});
```
or
```
const partialFoo = new Foo({
  baz: 'baz',
})
  .partial();
```
Either would be very useful for building 'incomplete' documents, such as the use case where a 3rd-party API needs supplied with some required fields and returns a completed document that your application will store. In the case of MongoDB, the engine creates the field `_id` via hashing upon insertion, then uses that field as an index key. You can set that field prior to calling the insertion method, but it's generally preferred to let Mongo handle it.

Because that field definitely _will_ exist when Mongo is queried and the returned document validated, it needs to be defined in the schema, and preferably it should not be `optional()` to ensure the document is authentic. However, that means that when you build and validate an object to be inserted e.g.
```
const newFoo = new Foo({
  bar: 42,
  baz: 'baz'
});

return db.collection.insertOne(newFoo);
```
it will fail validation because `_id` isn't there—because it doesn't exist yet. In that case, `.partial()` would make that field optional without disrupting the ability to validate it when queried later.

I've been working around this by defining `class PartialFoo extends Z.class(...) {}` and passing in trimmed-down versions of the complete schema, but it would be great to be able to do it without defining and keeping track of 'extra' classes.

**Comment by thawankeane** [comment]
Totally agree with this feature request,

@sam-goodwin I hadn't seen this issue when I opened #14, both requests are quite similar

As classes are always objects, I guess that we may just expose every method that a zod schema object has

**Comment by sam-goodwin** [comment]
Yeah I agree we should expose these features. Will tick these off on my next pass through 🫡

**Comment by sam-goodwin** [comment]
> @sam-goodwin we have any progress on this issue? — Sorry for rushing you
> 
> Let us know if you need some help

Pull requests are always welcome. If you feel strongly about a change, I'd be more than happy to collab on a PR.

No rush at all. If anything, I'm happy to see folks interested in this tool. The feedback has been awesome to get it to where it is today. Looks like there's still a few things to figure out though!

**Comment by sam-goodwin** [comment]
I'm looking at Zod's `pick` API and it's meh.

```ts
obj.pick({
  prop1: true,
  prop2: true;
})
```

I would have modeled it like so:

```ts
obj.pick("prop1", "prop2")
```

Curious to hear feedback on this. 

I'm leaning towards just aligning with Zod's schema even though I think it's sub-optimal. The more aligned we can be the better?

**Comment by sam-goodwin** [comment]
This is what i'm thinking for behavior:
```ts
test("ZodClass.pick returns a new Class with only those", () => {
  class User extends Z.class({
    username: z.string(),
    password: z.string(),
    age: z.number(),
  }) {}

  class Age extends User.pick({
    age: true,
  }) {
    getAge() {
      return this.age;
    }
  }

  const age = new Age({
    age: 1,
  });
  expect(age.getAge()).toEqual(1);

  expect(age instanceof User).toBe(false);

  () => {
    // @ts-expect-error - Age is not an instance of User
    age.getUsername();
  };
});
```

**Comment by sam-goodwin** [comment]
> I'm looking at Zod's `pick` API and it's meh.
> 
> ```ts
> obj.pick({
>   prop1: true,
>   prop2: true;
> })
> ```
> 
> I would have modeled it like so:
> 
> ```ts
> obj.pick("prop1", "prop2")
> ```
> 
> Curious to hear feedback on this.
> 
> I'm leaning towards just aligning with Zod's schema even though I think it's sub-optimal. The more aligned we can be the better?

Turns out I can support both with overloads :)

**Comment by thawankeane** [comment]
> Should `pick` just return a new schema and erase the lineage with the original class?

Don't know if it's possible but it would be great if we could pick/omit class methods/properties also

> This is what I'm thinking for behavior:

Wow! I really liked this one

> Turns out I can support both with overloads :)

Perfect!

**Comment by sam-goodwin** [comment]
Here's my analysis of the ZodObject utility methods and how they may translate to ZodClass

# CANNOT produce Sub-Types of a ZodClass
The following methods should create a new class lineage (i.e. they don't produce classes that are sub-types of the schema they are derived from):
1. `pick`
2. `omit`
3. `passthrough`
4. `partial`
5. `deepPartial`

# CAN produce a Sub-Type of a ZodClass

1. `required` - making all of the properties required should narrow the type and maintain the sub-type relationship
2. `strict`/`strip`/`catchall` - these are a bit weird since I don't capture extra keys on the derived class type. Perhaps I should?

Not totally sure about the following:
1. `extend`/`merge` - in some cases, it can create a sub-type, but not true in others.

If both `A` and `B` in `A.extend(B)` are ZodClasses, then we have a multiple inheritance situation. Not sure it's possible (or even advisable) to support multiple inheritance with a Prototype chain.

If `A` is a Class and `B` is a schema, then `A.extend(B)` could be a sub-type of `A`. However, there may be some nuance. According to the Zod docs, `.extend` can overwrite fields. If it overwrites them such that the derived type is not longer a sub-type, then we should not create a class.

> You can add additional fields to an object schema with the .extend method.
> You can use .extend to overwrite fields! Be careful with this power!

# Miscellaneous
1. `keyof` produces an enum. Nothing special to do here.
2. `shape` is already implemented

**Comment by sam-goodwin** [comment]
> Don't know if it's possible but it would be great if we could pick/omit class methods/properties also

I love the ambition! Let's think this through, where can it go wrong?

First, to pick a method, we need to grab it from the prototype of the source class. This is technically possible, but it can break in many ways, e.g. if that method calls another method that was not picked. I could just leave it as a foot-gun for the user to be aware of, but is this feature actually useful in practice? What would you use it for?

What does it mean to pick a property? Properties can be declared in many ways.

1. initialized in the body of the class
```ts
class Foo {
  prop = "value"
}
```

2. Which roughly translates to code that runs during the constructor call, similar to:

```ts
class Foo {
  constructor() {
    this.prop = "value:
  }
}
```

To keep this logic, we'll need the original prototype chain to be maintained in the new class, but that constructor may rely on fields that have been dropped, leading to runtime errors.

3. Declared as types and set by methods - `pick("prop")` will depend on `setProp` or else it'll never be set.
```ts
class Foo {
  prop: string;

  setProp() {
    this.prop = "value"
  }
}
```

4. `getter/setter` - this translates to methods on the prototype chain, which we already discussed the risks of.
```ts
class Foo {
  get foo() { return this._val }
  set foo(value: string) { this._val = "foo" }
}
```

5. All sorts of monkey patching techniques like `Object.assign`, `Object.defineProperty` etc.

I think it would be fun to implement but I'm not sure it's actually useful?

**Comment by thawankeane** [comment]
> First, to pick a method, we need to grab it from the prototype of the source class. This is technically possible, but it can break in many ways, e.g. if that method calls another method that was not picked. I could just leave it as a foot-gun for the user to be aware of, but is this feature actually useful in practice? What would you use it for?

> I think it would be fun to implement but I'm not sure it's actually useful?

Well thought — IMO we can keep this on the roadmap and for now just implement the pick/omit without the sub-types. If in the future someone shows a need then we consider implementing it

**Comment by sam-goodwin** [comment]
There are some other methods, not specific to objects, that we should also implement:

```ts
optional(): ZodOptional<this>;
nullable(): ZodNullable<this>;
nullish(): ZodNullable<ZodOptional<this>>;
array(): ZodArray<this>;
promise(): ZodPromise<this>;
or<T extends ZodTypeAny>(option: T): ZodUnion<[this, T]>;
and<T extends ZodTypeAny>(incoming: T): ZodIntersection<this, T>;
transform<NewOut>(transform: (arg: Output, ctx: RefinementCtx) => NewOut | Promise<NewOut>): ZodEffects<this, NewOut>;
default(def: util.noUndefined<Input>): ZodDefault<this>;
default(def: () => util.noUndefined<Input>): ZodDefault<this>;
brand<B extends string | number | symbol>(brand?: B): ZodBranded<this, B>;
catch(def: Input): ZodCatch<this>;
catch(def: () => Input): ZodCatch<this>;
describe(description: string): this;
pipe<T extends ZodTypeAny>(target: T): ZodPipeline<this, T>;
isOptional(): boolean;
isNullable(): boolean;
```

`optional` and `nullable` are already implemented. But It seems like I should also proxy these?

**Comment by thawankeane** [comment]
> But It seems like I should also proxy these?

As classes are always objects I'm not sure if we need these, can you imagine some use cases?

**Comment by sam-goodwin** [comment]
> > But It seems like I should also proxy these?
> 
> 
> 
> As classes are always objects I'm not sure if we need these, can you imagine some use cases?

```ts
User.or(Person)
User.array()
```

They're basically helpers that every zod type supports

**Comment by thawankeane** [comment]
> They're basically helpers that every zod type supports

I'm not 100% sure about these cause we could just use the `.schema` methods when #17 is done

Of course the richer the API better, but I'm not sure if we need to spend time implementing this right now

**Comment by sam-goodwin** [comment]
Trying to implement them led me to discover some nasty bugs though: https://github.com/sam-goodwin/zod-class/issues/18
