### ISSUE TITLE
Expose raw schema as static property

### ISSUE THREAD

**Issue by thawankeane** [sam-goodwin/zod-class#17]
In early versions, it was possible to use the raw schema using the `.schema` accessor, I believe that will be great if we return this feature so it's a good way to use zod-class classes with some other libraries that expect to use a `z.AnySchema`

The codes below exemplifies how it can be useful

```ts
import { z } from "zod";
import { Z } from "zod-class";

// zod-class class definition
class User extends Z.class({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string()
}) {}

// now lets say that you are using a library that expect you to pass a zod schema as argument

class UserDTO extends createZodDto(User) {} // 👈 type error cause `User` isn't a `z.AnySchema`

// what could be done (but a little verbose) is to wrap the class into a `z.object` and use the `.shape` property
class UserDTO extends createZodDto(z.object(User.shape)) {} // 👈 ok but verbose

```

Another possible way (still verbose) is to separate the schema definition from the class, but it will inflict [one of the reasons why this library exists](https://github.com/sam-goodwin/zod-class?tab=readme-ov-file#why)

```ts
import { z } from "zod";
import { Z } from "zod-class";

const UserSchema = z.object({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string()
});

class User extends Z.class(UserSchema) {}

class UserDTO extends createZodDto(UserSchema) {}
```

So I think if we went back to expose an static `.schema` property theses workarounds wouldn't need to exists

```ts
import { z } from "zod";
import { Z } from "zod-class";

class User extends Z.class({
  id: z.string().uuid(),
  email: z.string().email(),
  name: z.string()
}) {}

class UserDTO extends createZodDto(User.schema) {}
```

**Comment by sam-goodwin** [comment]
Do you have a link to `createZodDto`?

I would very much like a ZClass to be compatible with Zod's schema. I believe the ideal experience is:

```ts
class UserDTO extends createZodDto(User) {} // 👈 type error cause `User` isn't a `z.AnySchema`
```

The problem with `createZodDto(User.schema)` is if the DTO calls `schema.parse`, it won't return an instance of `User`, you'll get an object literal with the shape of `User.schema` (not the same thing).

I believe the reason `typeof User` is not a sub-type of `z.AnySchema`  is because I had to patch the `parse`, `extend`, etc. methods:

https://github.com/sam-goodwin/zod-class/blob/f1d40fe949d9ea88ccc1f740fbf2901f0accdfcf/src/index.ts#L33-L49

It may be possible to declare a wrapper around `createZodDto` that just casts away the error. I suspect any code expecting a Zod Schema would be compatible with a ZClass.

**Comment by sam-goodwin** [comment]
Oh, and I forgot. The `schema` property was renamed to `shape`:

https://github.com/sam-goodwin/zod-class/blob/f1d40fe949d9ea88ccc1f740fbf2901f0accdfcf/src/index.ts#L30-L32

You can try:
```ts
createDto(User.shape)
```

But remember, `User.shape.parse` will not return an instance of the `User` class.

**Comment by thawankeane** [comment]
> Do you have a link to `createZodDto`?

It was just an example but strongly based on [nestjs-zod](https://github.com/risen228/nestjs-zod?tab=readme-ov-file#creating-dto-from-zod-schema)



> The problem with `createZodDto(User.schema)` is if the DTO calls `schema.parse`, it won't return an instance of `User`, you'll get an object literal with the shape of `User.schema` (not the same thing).

Yeah, and that's exactly what is takes. If we want to be compatible with other libraries that just accept a native zod schema then we should expose somehow the schema that was passed when defining the class



> Oh, and I forgot. The `schema` property was renamed to `shape`:

Actually the `.shape` property it's a object containing the sub schema for each property in the root object schema

**Comment by sam-goodwin** [comment]
Ah, you're right! `shape` is not a Zod Schema.

It just occured to me that there is at least a nice workaround here.

I can add the schema to `ZodClass` and type it like this:
```ts
schema: z.ZodType<this>;
```

That way it will return an instance of `User`.

**Comment by thawankeane** [comment]
> That way it will return an instance of `User`.

I think that a better approach would be just return the original `ZodObject` that was passed in `.class` function
```ts
schema: z.ZodObject<Shape> // 👈 `Shape` is a `ZodClass` generic
```

**Comment by sam-goodwin** [comment]
Hmm, what's the benefit to that?

This approach works and maintains all of the type-safety:
<img width="649" alt="image" src="https://github.com/sam-goodwin/zod-class/assets/38672686/84ed1416-fc84-4590-b812-3f86e0662763">

**Comment by thawankeane** [comment]
> This approach works and maintains all of the type-safety:

Oh I misunderstood you, you're right, this approach will fit perfectly

**Comment by thawankeane** [comment]
Actually, there are some cases that should be covered that are very similar with #13, when using the `.schema()` method the `ZodObject` methods (like `.pick`, `.omit`) should also be exposed

**Comment by sam-goodwin** [comment]
<img width="695" alt="image" src="https://github.com/sam-goodwin/zod-class/assets/38672686/6f9834ea-8393-486b-9623-0508aa242aef">

**Comment by sam-goodwin** [comment]
> Actually, there are some cases that should be covered that are very similar with #13, when using the `.schema()` method the `ZodObject` methods (like `.pick`, `.omit`) should also be exposed

Totally, i'll add those methods in my next PR.

Currently sitting on a plane and port 22 doesn't work! ha

```
samgoodwin@Sams-MacBook-Pro zod-class % git push
kex_exchange_identification: read: Connection reset by peer
Connection reset by 140.82.113.3 port 22
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by thawankeane** [comment]
> Totally, i'll add those methods in my next PR.

Nailed it, thank you



> Currently sitting on a plane and port 22 doesn't work! ha

Haha, have a good flight Sam
