### ISSUE TITLE
Inherit methods from base class in extended class

### ISSUE THREAD

**Issue by gordongest** [sam-goodwin/zod-class#2]
Hi Sam,

Thanks for building `extend`! It's very useful in opening up inheritance patterns with `ZodClass`. In testing, I've noticed that the class instance returned by `extend` does implement type extension/narrowing exactly as you'd expect, but it doesn't inherit class methods declared on the base class—I could very well be incorrect, but I believe because its declared as a `static` method and therefore doesn't have any reference to the parent class?

As an example, it would be excellent to be able to do the following:

```
const fooShape = {
  foo: z.string()
}

class Foo extends ZodClass(fooShape) {
  getFoo() {
    return this.foo;
  }
}

const barShape = {
  foo: z.literal('forty-two'),
  bar: z.number()
}

class Bar extends Foo.extend(barShape) {
  getBar() {
    return this.bar;
  }
}

const barSchema = {
  foo: 'forty-two',
  bar: 42,
}

const bar = Bar.parse<Bar>(barSchema);

const fortyTwo: 'forty-two' = bar.getFoo(); <— this method reference is currently lost
```
Does this seem feasible given how JS handles prototypal inheritance?

**Comment by sam-goodwin** [comment]
Ah, good catch. The method is technically there, as this works:

```ts
expect(bar.getFoo()).toEqual("forty-two")
```

Problem is that it's not captured in the type because the type uses the generated class and not the one you're extending.

```ts
function ZodClass(..) {
  return class { .. } // <- the type reflects this type
}

class Foo extends ZodClass(..) {} // <- it needs to be this type
```

This is a similar problem to why `Foo.parse` doesn't return an instance of `Foo` and you need to do `Foo.parse<Foo>()`. In the types, we don't know about Foo yet.

I'll play with it. Maybe I can solve that problem.

**Comment by sam-goodwin** [comment]
In its most basic form, TypeScript doesn't allow using `this` in a static context. This could be a problem.

```ts
class Foo {
  // Error: A 'this' type is available only in a non-static member of a class or interface.ts(2526)
  static getInstance(): this {}
}

class Bar extends Foo {}

Bar.getInstance() // any
```

**Comment by sam-goodwin** [comment]
Also can't make it by working around `class` limitation:

```ts
interface FooCtor {
  getInstance(): InstanceType<this>;
  new(): {
    onlyFoo(): void;
  };
}

declare const Foo: FooCtor;

class Bar extends Foo {
  onlyBar(): void {}
}

Bar.getInstance().onlyFoo();
// @ts-expect-error - Property 'onlyBar' does not exist on type '{ onlyFoo(): void; }'.ts(2339)
Bar.getInstance().onlyBar();
```

**Comment by sam-goodwin** [comment]
Am now thinking that placing the `extends` method on the generated class is wrong. Instead, we need a helper that can capture the concrete class instead of the abstract one.

E.g.
```ts
class Bar extends $(Foo).extend({..}) {}
```

Here, `$(Foo)` is operating on the type `Foo` which includes any methods you add. This should help us work around the problem. It also might be a better way of working in general.

**Comment by sam-goodwin** [comment]
Sidebar: Thinking of other utilities like:

```ts
$(Foo).pick("field1", "field2")
$(Foo).omit("field1", "field2")
```

**Comment by sam-goodwin** [comment]
Came up with a solution: https://github.com/sam-goodwin/zod-class/pull/3

**Comment by sam-goodwin** [comment]
Published as version `0.0.4`

**Comment by gordongest** [comment]
> Ah, good catch. The method is technically there, as this works:
> 
> ```ts
> expect(bar.getFoo()).toEqual("forty-two")
> ```
> 
> Problem is that it's not captured in the type because the type uses the generated class and not the one you're extending.
> 
> ```ts
> function ZodClass(..) {
>   return class { .. } // <- the type reflects this type
> }
> 
> class Foo extends ZodClass(..) {} // <- it needs to be this type
> ```
> 
> This is a similar problem to why `Foo.parse` doesn't return an instance of `Foo` and you need to do `Foo.parse<Foo>()`. In the types, we don't know about Foo yet.
> 
> I'll play with it. Maybe I can solve that problem.

Yeah, that is what I suspected. I attempted to build an interface for an `ExtendedZodClass<C extends ZodClass>` that would enable returning an instance of `ExtendedZodClass<this>` which actually did bring back the method reference as far as the linter was concerned, but ran into hangups around the typing for `ZodClass` at build.

**Comment by sam-goodwin** [comment]
> Yeah, that is what I suspected. I attempted to build an interface for an ExtendedZodClass<C extends ZodClass> that would enable returning an instance of ExtendedZodClass<this> which actually did bring back the method reference as far as the linter was concerned, but ran into hangups around the typing for ZodClass at build.

I would love to see your approach!

**Comment by gordongest** [comment]
Sure!

First, I declared a barebones interface for `ExtendedZodClass`:

```
export interface ExtendedZodClass<T extends ZodRawShape> extends ZodClass<T> {

}
```

Then, refactored the interface for `ZodClass` to reflect that change:

```
export interface ZodClass<T extends ZodRawShape>
  extends Omit<
    ZodObject<T>,
    "parse" | "parseAsync" | "safeParse" | "safeParseAsync" | "extend"
    > {
  extend<U extends ZodRawShape, C extends ZodClass<any>> (
    augmentation: U
  ): ExtendedZodClass<U, ZodClass<U>>;
...
```

I removed the `static` attribute from `extend`'s declaration:

```
...
extend<T extends ZodRawShape, C extends this>(augmentation: T): ExtendedZodClass<C> {
  const augmented = _schema.extend(augmentation);
  // @ts-ignore
  return class extends this {
    static schema = augmented;
    constructor(value: ZodValue<ZodObject<T>>) {
      super(value);
      return Object.assign(this, augmented.parse(value) as ExtendedZodClass<C>);
    }
  };
}
```

This is something of a mess—I'm pretty bad at generics—but it confirmed a hunch that the `static` method declaration was causing the interpreter to lose track of the reference to `this`, as it began recognizing inherited methods and class fields. At build the TS compiler would throw a series of errors around `ExtendedZodClass` not satisfying the typing for `ZodClass`, which I wasn't able to work through.

I'm not sure if that approach would really solve the issue of the compiler not knowing about `Foo` at generation, so your solution is probably the better way.
