### ISSUE TITLE
Optional params in schema are required in class creation.

### ISSUE THREAD

**Issue by jcarlsonautomatiq** [sam-goodwin/zod-class#22]
First off great library and it makes some of the worst problems with Zod go away!  Being able to add methods to a validator is fantastic.  The bug / feature that I am running into is there any way to make the optional handlers make the class creation play nice?

```
// Some file.ts in typescript
class drat extends Z.class({
  name: z.string().optional(),
}) {}

const ab = {};
new drat(ab); 

Argument of type '{}' is not assignable to parameter of type '{ name: string; }'.
  Property 'name' is missing in type '{}' but required in type '{ name: string; }'.ts(2345)
```

We can always get around it by just change the params to an any and then letting the validation logic handle anything illegal but it would be nice if optional was optional.

**Comment by sam-goodwin** [comment]
I'm surprised that doesn't work. I'll take a look tonight, but I thought that was working. There's no explicit test to check optional though. Thanks for reporting.

**Comment by jcarlsonautomatiq** [comment]
Thanks for making this! I was creating some really ugly duplicate classes without it :).  Having a class that does validation on create is fantastic!

**Comment by sam-goodwin** [comment]
You're welcome! I'll try and squeeze out a fix later today :)

**Comment by sam-goodwin** [comment]
Should be fixed in `0.0.13` - LMK if you run into trouble and thanks for reporting!

**Comment by jcarlsonautomatiq** [comment]
Seems to work out ok on TS compile now!  The VSCode side of things is being dumb on the definition when it tries to "help" but runtime is fine.  Thanks a lot :)

```
const optionalEnum = z.enum(['a', 'b']);
const schema = z.object({
  varOptional: z.string().optional(),
  e: optionalEnum.optional(),
  arr: z.string().array().optional(),
});
export class TestClass extends Z.class({
  ...schema._def.shape(),
}) {}
new TestClass({});
```
<img width="293" alt="Screenshot 2024-04-01 at 8 51 49 AM" src="https://github.com/sam-goodwin/zod-class/assets/149196551/c6228e16-a63d-4425-998a-b0df7e7af555">

**Comment by sam-goodwin** [comment]
Try passing the attributes directly 

```
class MySchema extends Z.class({
  varOptional: z.string().optional(),
  e: optionalEnum.optional(),
  arr: z.string().array().optional(),
}) {}
```
