### ISSUE TITLE
Error vite build "isPromise" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by hepr** [sam-goodwin/zod-class#25]
Vite version : v5.3.5

vite v5.3.5 building for production...
[plugin:vite:resolve] [plugin vite:resolve] Module "node:util/types" has been externalized for browser compatibility, imported by "/Users/herve/Documents/www/k22-app/node_modules/zod-class/lib/esm/index.js". See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.
✓ 3798 modules transformed.
x Build failed in 8.02s
error during build:
node_modules/zod-class/lib/esm/index.js (7:9): "isPromise" is not exported by "__vite-browser-external", imported by "node_modules/zod-class/lib/esm/index.js".
file: /Users/herve/Documents/www/k22-app/node_modules/zod-class/lib/esm/index.js:7:9

5: import { ZodArray, ZodNullable, ZodOptional, ZodPromise, object, z, } from "zod";
6: import { toPascalCase } from "./to-pascal-case.js";
7: import { isPromise } from "node:util/types";
            ^
8: const IS_ZOD_CLASS = Symbol.for("zod-class");
9: export const Z = {...

Is there a solution ?

**Comment by sam-goodwin** [comment]
Hm, could it be a problem with `node:util` maybe? Do you happen to have a way t easily reproduce this?

**Comment by sam-goodwin** [comment]
I could switch the use of isPromise to a simple duck-typing check? e.g.`typeof f.then === 'function' and typeof f.catch == 'function'`

**Comment by sam-goodwin** [comment]
There's also this: https://www.npmjs.com/package/vite-plugin-node-polyfills

**Comment by rsan-one-network** [comment]
I created a PR that would probably fix this issue

**Comment by sledorze** [comment]
We have the problem on the front end side

**Comment by sam-goodwin** [comment]
This should be fixed in `zod-class@0.0.14`, can you please confirm?

**Comment by sledorze** [comment]
Good for me too (in prod :) )
