### ISSUE TITLE
Missing .class method in 0.0.6

### ISSUE THREAD

**Issue by gordongest** [sam-goodwin/zod-class#9]
It appears that the `...extends Z.class(...)` usage pattern as specified in the `README` is not available as of `0.0.6`. It seems like that change may not have been carried in the most recent PR, as `index.ts` does not include it. Currently, there does not appear to be a way to define new classes in `0.0.6`, as `... extends Z(...)` is also not a member on the constructor.

**Comment by sam-goodwin** [comment]
Fixed in 0.0.9

Lesson is that adding properties to a function works when importing source `.ts` files but is lost during compilation.

I fixed by adding an explicit interface for `Z`

**Comment by sam-goodwin** [comment]
Curious to hear your feedback on https://github.com/sam-goodwin/zod-class/issues/7
